site_name: "Zhanpeng Chen's Homepage"
site_author: 'Zhanpeng Chen'
copyright: '&copy; 2024-2026 Zhanpeng Chen'
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: white
    accent: orange
  favicon: images/favicon.png
  icon:
    logo: material/account-school
  font:
    text: Gabarito

plugins:
  []

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:troychen927@stu.pku.edu.cn
    - icon: academicons/google-scholar
      link: https://scholar.google.com/citations?user=ca5deHsAAAAJ&hl=zh-CN
    - icon: fontawesome/brands/github
      link: https://github.com/kzhpchen
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zhanpeng-chen-421918305/
extra_css:
  - stylesheets/extra.css
